#:schema node_modules/wrangler/config-schema.json
name = "onview"
main = "src/index.tsx"
compatibility_date = "2024-09-03"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "onview-artwork"
database_id = "a8fcbecd-e4cc-43e8-813c-90732a0d3323"

[[vectorize]]
binding = "VECTORIZE"
index_name = "artwork-index"
